name = "IPGBs"
uuid = "cd26b91b-75b4-4f6e-a355-d2a0d136006d"
authors = ["Gabriel Langeloh <gmlangeloh@inf.ufrgs.br> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
